---
- name: Wait for connection to be available and manage Docker containers
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-tcc
    ansible_aws_ssm_region: us-east-1
  tasks:
    - name: Wait for connection
      wait_for_connection:

    - name: Ensure git is installed
      become: true
      package:
        name: git
        state: present

    - name: Clone or update the repository
      become: true
      git:
        repo: "git@github.com:FaceCare/tcc-cco-2024-face-care.git"
        dest: "~/tcc/tcc-cco-2024-face-care"
        version: dev
        force: yes

    - name: Stop Docker Compose services
      become: true
      shell: docker-compose stop
      args:
        chdir: ~/tcc/tcc-cco-2024-face-care/.docker/

    - name: Remove Docker image
      become: true
      community.docker.docker_image:
        name: docker_backend
        state: absent
        force_absent: true

    - name: Build and start Docker Compose services
      become: true
      shell: docker-compose up --build -d -V
      args:
        chdir: ~/tcc/tcc-cco-2024-face-care/.docker/
