---
# Wait for SSM Agent to be available on the Instance
- name: Wait for connection to be available and install Docker
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-tcc
    ansible_aws_ssm_region: us-east-1
  tasks:
    - name: Wait for connection
      wait_for_connection:

    # - name: Change to user home directory
    #   ansible.builtin.command: cd ~

    # - name: Check if tcc directory exists
    #   ansible.builtin.stat:
    #     path: ~/tcc
    #   register: tcc_dir

    # - name: Create tcc directory if it does not exist
    #   ansible.builtin.file:
    #     path: ~/tcc
    #     state: directory
    #   when: not tcc_dir.stat.exists

    # - name: Change to tcc directory
    #   ansible.builtin.shell: cd ~/tcc

    - name: Update apt package index
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade all installed packages
      apt:
        upgrade: dist
      become: yes

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Set up the stable Docker repository
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes

    - name: Update apt package index again
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      become: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Download Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose
      become: yes

    - name: Apply executable permissions to Docker Compose binary
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: "0755"
      become: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version

    - debug:
        msg:
          - "Docker version: {{ docker_version.stdout }}"
          - "Docker Compose version: {{ docker_compose_version.stdout }}"








 install python3-pip