---
- name: Wait for connection to be available and install Docker
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-tcc
    ansible_aws_ssm_region: us-east-1
  tasks:
    - name: Wait for connection
      wait_for_connection:

    - name: Deploy tratamento imagem
      become: true
      become_user: root
      shell: |
        cd ~/tcc/tcc-cco-2024-face-care/
        git checkout dev
        git pull
        cd tratamentoImagem/src/
        python3 -m pip install -r requirements.txt
        apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
      ignore_errors: yes

    - name: Add cronjob to run app.py every 5 minutes
      cron:
        name: "Run app.py every 5 minutes"
        minute: "*/5"
        job: "cd ~/tcc/tcc-cco-2024-face-care/tratamentoImagem/src/ && python3 app.py"
        state: present
