---
- name: Wait for connection to be available and install Docker
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-tcc
    ansible_aws_ssm_region: us-east-1
  tasks:
    - name: Wait for connection
      wait_for_connection:

    - name: Ensure git is installed
      become: true
      package:
        name: git
        state: present

    - name: Ensure Python 3 and pip are installed
      become: true
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure required packages are installed
      become: true
      package:
        name:
          - ffmpeg
          - libsm6
          - libxext6
        state: present

    - name: Clone or update the repository
      become: true
      git:
        repo: "git@github.com:FaceCare/tcc-cco-2024-face-care.git"
        dest: "~/tcc/tcc-cco-2024-face-care"
        version: dev
        force: yes

    - name: Install Python requirements
      become: true
      pip:
        requirements: "~/tcc/tcc-cco-2024-face-care/tratamentoImagem/src/requirements.txt"
        state: present
        executable: pip3

    - name: Add cronjob to run app.py every 5 minutes
      become: true
      cron:
        name: "Run app.py every 5 minutes"
        minute: "*/5"
        job: "cd ~/tcc/tcc-cco-2024-face-care/tratamentoImagem/src/ && python3 app.py"
        state: present
