name: Deploy to AWS

on:
  push:
    branches:
      - feat/backend*

jobs:
  deployBackend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible
        run: python3 -m pip install ansible

      - name: Install Ansible Galaxy collection
        run: ansible-galaxy collection install amazon.aws

      - name: Install Python dependencies for Ansible AWS integration
        run: python3 -m pip install boto3 botocore

      - name: Check Python version
        run: python --version

      - name: Check Ansible version
        run: ansible --version

      - name: Configure AWS CLI credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set aws_session_token $AWS_SESSION_TOKEN
          aws configure set default.region "us-east-1"

      - name: Install all requirements.txt files
        run: find . -name "requirements.txt" -exec python3 -m pip install -r {} \;

      - name: Verify boto3 and botocore installation
        run: |
          python3 -c "import boto3; print(boto3.__version__)"
          python3 -c "import botocore; print(botocore.__version__)"

      - name: Verify ansible directory contents
        run: |
          echo "Contents of ansible directory:"
          ls -la ansible/

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i aws_ec2.yml backend.yaml -e "ansible_python_interpreter=/usr/bin/python3" -v
