name: Deploy backend to AWS

on:
  push:
    branches:
      - test

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible and dependencies
        run: |
          python3 -m pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Install all requirements.txt files
        run: find ${{ github.workspace }}/ -name "requirements.txt" -exec python3 -m pip install -r {} \;

  configure-aws:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set aws_session_token $AWS_SESSION_TOKEN
          aws configure set default.region "us-east-1"

  run-ansible-playbook:
    runs-on: ubuntu-latest
    needs: [configure-aws, setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: pip freeze
        run: |
          echo "pip freeze:"
          pip freeze

      - name: Verify ansible directory contents
        run: |
          echo "Contents of ansible directory:"
          ls -la ${{ github.workspace }}/ansible

      - name: Run Ansible playbook
        run: |
          cd ${{ github.workspace }}/ansible
          ansible-playbook -i aws_ec2.yml backend.yaml -e "ansible_python_interpreter=/usr/bin/python3"
